include("mixed_tests.jl")
include("quadratics.jl")
include("acceleration.jl")
include("preconditioning.jl")
include("directsearch/neldermead.jl")
include("directsearch/randomsearch.jl")
include("randomsearch/apso.jl")
